//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WellCalculations2010.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double DistFromScale {
            get {
                return ((double)(this["DistFromScale"]));
            }
            set {
                this["DistFromScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double VertScaleWidth {
            get {
                return ((double)(this["VertScaleWidth"]));
            }
            set {
                this["VertScaleWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int InterpolatedPointsNumber {
            get {
                return ((int)(this["InterpolatedPointsNumber"]));
            }
            set {
                this["InterpolatedPointsNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double SolidEarthHatchDist {
            get {
                return ((double)(this["SolidEarthHatchDist"]));
            }
            set {
                this["SolidEarthHatchDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double VertScaleHeight {
            get {
                return ((double)(this["VertScaleHeight"]));
            }
            set {
                this["VertScaleHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5")]
        public double VertScaleFontSize {
            get {
                return ((double)(this["VertScaleFontSize"]));
            }
            set {
                this["VertScaleFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double VertScaleTextDist {
            get {
                return ((double)(this["VertScaleTextDist"]));
            }
            set {
                this["VertScaleTextDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double VertScaleTableDist {
            get {
                return ((double)(this["VertScaleTableDist"]));
            }
            set {
                this["VertScaleTableDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsSplitByDistance {
            get {
                return ((bool)(this["IsSplitByDistance"]));
            }
            set {
                this["IsSplitByDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("297")]
        public double SplitDistance {
            get {
                return ((double)(this["SplitDistance"]));
            }
            set {
                this["SplitDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsTableConsidered {
            get {
                return ((bool)(this["IsTableConsidered"]));
            }
            set {
                this["IsTableConsidered"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsFullVertScaleRullerReq {
            get {
                return ((bool)(this["IsFullVertScaleRullerReq"]));
            }
            set {
                this["IsFullVertScaleRullerReq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double WellMarkSize {
            get {
                return ((double)(this["WellMarkSize"]));
            }
            set {
                this["WellMarkSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double PlanarTextDistFromMark {
            get {
                return ((double)(this["PlanarTextDistFromMark"]));
            }
            set {
                this["PlanarTextDistFromMark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double WellPlanarTextSize {
            get {
                return ((double)(this["WellPlanarTextSize"]));
            }
            set {
                this["WellPlanarTextSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddHardEarth {
            get {
                return ((bool)(this["AddHardEarth"]));
            }
            set {
                this["AddHardEarth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double AddHardEarthDist {
            get {
                return ((double)(this["AddHardEarthDist"]));
            }
            set {
                this["AddHardEarthDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DrawWells {
            get {
                return ((bool)(this["DrawWells"]));
            }
            set {
                this["DrawWells"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DrawContents {
            get {
                return ((bool)(this["DrawContents"]));
            }
            set {
                this["DrawContents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DrawEarthSurfaces {
            get {
                return ((bool)(this["DrawEarthSurfaces"]));
            }
            set {
                this["DrawEarthSurfaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DrawHardEarthSurfaces {
            get {
                return ((bool)(this["DrawHardEarthSurfaces"]));
            }
            set {
                this["DrawHardEarthSurfaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DrawTable {
            get {
                return ((bool)(this["DrawTable"]));
            }
            set {
                this["DrawTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DrawScaleRuller {
            get {
                return ((bool)(this["DrawScaleRuller"]));
            }
            set {
                this["DrawScaleRuller"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsEarthSurface3dNeeded {
            get {
                return ((bool)(this["IsEarthSurface3dNeeded"]));
            }
            set {
                this["IsEarthSurface3dNeeded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsGoldBlock3dNeeded {
            get {
                return ((bool)(this["IsGoldBlock3dNeeded"]));
            }
            set {
                this["IsGoldBlock3dNeeded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsHardEarth3dNeeded {
            get {
                return ((bool)(this["IsHardEarth3dNeeded"]));
            }
            set {
                this["IsHardEarth3dNeeded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsMode3d {
            get {
                return ((bool)(this["IsMode3d"]));
            }
            set {
                this["IsMode3d"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LicenseTest {
            get {
                return ((string)(this["LicenseTest"]));
            }
            set {
                this["LicenseTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double IsolineStep {
            get {
                return ((double)(this["IsolineStep"]));
            }
            set {
                this["IsolineStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsIsolinesNeeded {
            get {
                return ((bool)(this["IsIsolinesNeeded"]));
            }
            set {
                this["IsIsolinesNeeded"] = value;
            }
        }
    }
}
